    create table cliente (
        categoria tinyint check (categoria between 0 and 2),
        atualizado_em timestamp(6) with time zone,
        criado_em timestamp(6) with time zone,
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        cpf varchar(255),
        email varchar(255),
        localidade varchar(255),
        nome varchar(255),
        numero varchar(255),
        rua varchar(255),
        senha varchar(255),
        uf varchar(255),
        primary key (id)
    );
 