       	create table conta (
        saldo numeric(38,2),
        taxa_manutecao numeric(38,2),
        taxa_rendimento numeric(38,2),
        cliente_id bigint not null,
        criado_em timestamp(6) with time zone,
        id bigint generated by default as identity,
        tipo_conta varchar(31) not null,
        agencia varchar(255),
        numero varchar(255),
        primary key (id)
    );

 