  create table cartao (
        limite_credito numeric(38,2),
        limite_diario numeric(38,2),
        limite_diario_utilizado numeric(38,2),
        limite_utilizado numeric(38,2),
        status tinyint check (status between 0 and 1),
        conta_id bigint,
        id bigint generated by default as identity,
        tipo_cartao varchar(31) not null,
        numero varchar(255),
        senha varchar(255),
        primary key (id)
    );